"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, CalendarDays, ChevronRight, FileText, HeartPulse, Plus, Search, Settings, Stethoscope, UserRound, X, ShieldCheck } from "lucide-react";
import { createPatient, listPatients, type Patient } from "@/lib/data-provider";

const nav = [["/", "Beranda"], ["/patients", "Pasien"], ["/records", "Rekam Medis"], ["/prescriptions", "Resep"], ["/clinical", "Clinical Assistant"], ["/tools", "Tools"], ["/templates", "Template"], ["/schedule", "Jadwal"], ["/reports", "Laporan"], ["/settings", "Pengaturan"]];

function ageFromDate(date: string) { if (!date) return "-"; const birth = new Date(date); const now = new Date(); let age = now.getFullYear() - birth.getFullYear(); const m = now.getMonth() - birth.getMonth(); if (m < 0 || (m === 0 && now.getDate() < birth.getDate())) age--; return age; }

export default function PatientsPage() {
  const [patients, setPatients] = useState<Patient[]>([]);
  const [q, setQ] = useState("");
  const [selected, setSelected] = useState<Patient | null>(null);
  const [showNew, setShowNew] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ name: "", medical_record_no: "", sex: "Laki-laki" as Patient["sex"], birth_date: "", phone: "", allergies: [] as string[] });

  useEffect(() => { listPatients().then((rows) => { setPatients(rows); setSelected(rows[0] ?? null); }); }, []);
  const filtered = useMemo(() => patients.filter((p) => `${p.name} ${p.medical_record_no} ${p.phone ?? ""}`.toLowerCase().includes(q.toLowerCase())), [patients, q]);

  async function save() {
    if (!form.name.trim()) return;
    setSaving(true);
    try { const created = await createPatient(form); setPatients((old) => [created, ...old]); setSelected(created); setShowNew(false); setForm({ name: "", medical_record_no: "", sex: "Laki-laki", birth_date: "", phone: "", allergies: [] }); }
    finally { setSaving(false); }
  }

  return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">D</div><div><strong>Dokter Jaga</strong><span>Clinical Intelligence</span></div></div><div className="doctor-mini"><div className="avatar">DP</div><div><b>dr. Dwi Pratama</b><small>Dokter Umum</small></div></div><nav>{nav.slice(0,7).map(([href,label])=><a key={href} href={href} className={`nav-item ${label === "Pasien" ? "active" : ""}`}>{label === "Pasien" ? <UserRound size={17}/> : label === "Rekam Medis" ? <FileText size={17}/> : label === "Resep" ? <Activity size={17}/> : label === "Clinical Assistant" ? <HeartPulse size={17}/> : <Stethoscope size={17}/>}<span>{label}</span>{label === "Clinical Assistant" && <i>AI</i>}</a>)}</nav><div className="sidebar-bottom">{nav.slice(7).map(([href,label])=><a key={href} href={href} className="nav-item">{label === "Jadwal" ? <CalendarDays size={17}/> : label === "Pengaturan" ? <Settings size={17}/> : <Activity size={17}/>}<span>{label}</span></a>)}</div></aside>
    <section className="content"><header className="topbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, nomor RM, atau telepon..."/></div><div className="top-actions"><div className="top-doctor"><div className="avatar small">DP</div><span>dr. Dwi</span></div></div></header>
      <div className="page-head"><div><p className="eyebrow">PATIENT DIRECTORY</p><h1>Daftar Pasien</h1><p className="muted">Identitas pasien tersimpan terpisah dari encounter untuk alur rekam medis yang konsisten.</p></div><button className="primary" onClick={()=>setShowNew(true)}><Plus size={15}/> Pasien Baru</button></div>
      <div className="quick-grid"><div className="quick-card"><div className="quick-icon blue"><UserRound size={17}/></div><div><b>{patients.length}</b><span>Pasien terdaftar</span></div></div><div className="quick-card"><div className="quick-icon teal"><Activity size={17}/></div><div><b>Persistent</b><span>Supabase-ready</span></div></div><div className="quick-card"><div className="quick-icon purple"><HeartPulse size={17}/></div><div><b>Encounter</b><span>Terhubung ke RM</span></div></div><div className="quick-card"><div className="quick-icon indigo"><ShieldCheck size={17}/></div><div><b>RLS</b><span>Akses berbasis dokter</span></div></div></div>
      <div className="workspace-grid" style={{gridTemplateColumns:"1.35fr .65fr",alignItems:"start"}}><section className="panel" style={{padding:16}}><div className="panel-head"><div><h2>Patient list</h2><p>{filtered.length} pasien ditampilkan</p></div></div>{filtered.map(p=><button key={p.id} className="patient-row" onClick={()=>setSelected(p)}><div className="patient-avatar">{p.name.split(" ").map(x=>x[0]).join("")}</div><div className="patient-info"><b>{p.name}</b><span>{p.medical_record_no} · {p.sex} · {ageFromDate(p.birth_date)} th · {p.phone || "Telepon belum diisi"}</span></div><ChevronRight size={15} style={{marginLeft:10,color:"#a0aabd"}}/></button>)}</section>
        <aside className="panel" style={{padding:16}}>{selected ? <><div className="panel-head"><div><p className="eyebrow">PATIENT SUMMARY</p><h2>{selected.name}</h2><p>{selected.medical_record_no} · {selected.sex} · {ageFromDate(selected.birth_date)} tahun</p></div><button className="icon-btn" onClick={()=>setSelected(null)}><X size={15}/></button></div><div className="patient-banner" style={{marginTop:6}}><div className="patient-avatar large">{selected.name.split(" ").map(x=>x[0]).join("")}</div><div><b>{selected.phone || "Telepon belum diisi"}</b><span>Alergi: {(selected.allergies ?? []).join(", ") || "Belum dicatat"}</span></div></div><div className="info-columns" style={{gridTemplateColumns:"1fr 1fr",marginTop:10}}><div><h4>Identitas</h4><div className="check-line">Tanggal lahir · {selected.birth_date || "-"}</div><div className="check-line">No. RM · {selected.medical_record_no}</div></div><div><h4>Quick actions</h4><a className="nav-item" style={{height:30,padding:0}} href={`/clinical?patient=${encodeURIComponent(selected.id)}`}>↗ Clinical Assistant</a><a className="nav-item" style={{height:30,padding:0}} href={`/records?patient=${encodeURIComponent(selected.id)}`}>↗ Rekam Medis</a><a className="nav-item" style={{height:30,padding:0}} href={`/prescriptions?patient=${encodeURIComponent(selected.id)}`}>↗ Buat Resep</a></div></div><button className="primary wide" onClick={()=>window.location.href=`/clinical?patient=${encodeURIComponent(selected.id)}`}>Mulai Encounter Baru <ChevronRight size={15}/></button></> : <div style={{padding:30,textAlign:"center",color:"#7c8799"}}>Pilih pasien untuk melihat ringkasan.</div>}</aside></div>
      {showNew&&<div onClick={()=>setShowNew(false)} style={{position:"fixed",inset:0,background:"#0f172a66",display:"grid",placeItems:"center",zIndex:50}}><div className="panel" onClick={e=>e.stopPropagation()} style={{width:"min(520px,92vw)",padding:20}}><div className="panel-head"><div><p className="eyebrow">NEW PATIENT</p><h2>Tambah pasien</h2></div><button className="icon-btn" onClick={()=>setShowNew(false)}><X/></button></div><div className="info-columns" style={{gridTemplateColumns:"1fr 1fr",border:0,padding:0}}><label className="modal-card">Nama<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nama lengkap"/></label><label className="modal-card">No. RM<input value={form.medical_record_no} onChange={e=>setForm({...form,medical_record_no:e.target.value})} placeholder="RM-001252"/></label><label className="modal-card">Tanggal lahir<input value={form.birth_date} onChange={e=>setForm({...form,birth_date:e.target.value})} type="date"/></label><label className="modal-card">Jenis kelamin<select value={form.sex} onChange={e=>setForm({...form,sex:e.target.value as Patient["sex"]})}><option>Laki-laki</option><option>Perempuan</option></select></label><label className="modal-card" style={{gridColumn:"1/-1"}}>No. telepon<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="08xx"/></label></div><button className="primary wide" disabled={saving} onClick={save}>{saving ? "Menyimpan..." : "Simpan Pasien"}</button></div></div>}
    </section></main>
}
