"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CalendarDays, ChevronRight, Download, FileText, HeartPulse, Search, UserRound, Activity, Stethoscope } from "lucide-react";
import { listEncounters, listPatients, type Encounter, type Patient } from "@/lib/data-provider";

export default function RecordsPage(){
  const [patients,setPatients]=useState<Patient[]>([]); const [records,setRecords]=useState<Encounter[]>([]); const [q,setQ]=useState(""); const [active,setActive]=useState<Encounter|null>(null);
  useEffect(()=>{ Promise.all([listPatients(),listEncounters()]).then(([p,e])=>{setPatients(p);setRecords(e);setActive(e[0]??null);}); },[]);
  const patientMap=useMemo(()=>new Map(patients.map(p=>[p.id,p])),[patients]);
  const filtered=useMemo(()=>records.filter(r=>{const p=patientMap.get(r.patient_id); return `${p?.name??""} ${p?.medical_record_no??""} ${r.chief_complaint??""} ${r.assessment??""}`.toLowerCase().includes(q.toLowerCase());}),[records,patientMap,q]);
  const selectedPatient=active?patientMap.get(active.patient_id):null;
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">D</div><div><strong>Dokter Jaga</strong><span>Clinical Intelligence</span></div></div><div className="doctor-mini"><div className="avatar">DP</div><div><b>dr. Dwi Pratama</b><small>Dokter Umum</small></div></div><nav>{[["/","Beranda"],["/patients","Pasien"],["/records","Rekam Medis"],["/prescriptions","Resep"],["/clinical","Clinical Assistant"],["/tools","Tools"],["/templates","Template"]].map(([href,label])=><a key={href} className={`nav-item ${label==="Rekam Medis"?"active":""}`} href={href}><FileText size={17}/><span>{label}</span>{label==="Clinical Assistant"&&<i>AI</i>}</a>)}</nav><div className="sidebar-bottom"><a className="nav-item" href="/schedule"><CalendarDays size={17}/>Jadwal</a><a className="nav-item" href="/reports"><Activity size={17}/>Laporan</a><a className="nav-item" href="/settings"><Stethoscope size={17}/>Pengaturan</a></div></aside>
  <section className="content"><header className="topbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari rekam medis, pasien, diagnosis..."/></div></header><div className="page-head"><div><p className="eyebrow">MEDICAL RECORDS</p><h1>Rekam Medis</h1><p className="muted">Timeline encounter terhubung dengan patient master dan dapat diteruskan ke Clinical Assistant.</p></div><button className="primary" onClick={()=>window.print()}><Download size={14}/> Export</button></div>
  <div className="workspace-grid" style={{gridTemplateColumns:"1.15fr .85fr",alignItems:"start"}}><section className="panel" style={{padding:16}}><div className="panel-head"><div><h2>Encounter timeline</h2><p>{filtered.length} record</p></div></div>{filtered.map(r=>{const p=patientMap.get(r.patient_id); return <button className="patient-row" key={r.id} onClick={()=>setActive(r)}><div className="quick-icon blue" style={{width:32,height:32}}><FileText size={15}/></div><div className="patient-info"><b>{p?.name??"Pasien"} <span style={{display:"inline",marginLeft:5,fontSize:7,color:r.status==="signed"?"#138873":"#a36c10"}}>{r.status}</span></b><span>{r.created_at?new Date(r.created_at).toLocaleString("id-ID"):"Waktu tidak tersedia"} · {r.id.slice(0,12)}</span><span>{r.chief_complaint||"Keluhan belum diisi"}</span></div><ChevronRight size={15} style={{color:"#9aa4b4"}}/></button>})}</section>
  <aside className="panel" style={{padding:18}}>{active?<><p className="eyebrow">RECORD PREVIEW</p><div className="panel-head"><div><h2>{selectedPatient?.name??"Pasien"}</h2><p>{selectedPatient?.medical_record_no??""}</p></div><ArrowUpRight size={16} style={{color:"#2563eb"}}/></div><div className="patient-banner"><div className="patient-avatar large">{(selectedPatient?.name??"P").split(" ").map(x=>x[0]).join("")}</div><div><b>{active.assessment||"Diagnosis belum ditetapkan"}</b><span>{active.created_at?new Date(active.created_at).toLocaleString("id-ID"):""}</span></div></div><div style={{marginTop:14}}><div className="soap"><b>S</b><span>{active.subjective||active.chief_complaint||"Belum ada data subjektif."}</span></div><div className="soap"><b>O</b><span>{active.objective||"Belum ada data objektif."}</span></div><div className="soap"><b>A</b><span>{active.assessment||"Belum ada diagnosis kerja."}</span></div><div className="soap"><b>P</b><span>{active.plan||"Belum ada rencana."}</span></div></div><div className="warning" style={{marginTop:12}}><HeartPulse size={14}/><span>Review dokter diperlukan sebelum encounter ditandatangani sebagai catatan final.</span></div><button className="primary wide" onClick={()=>window.location.href=`/clinical?patient=${encodeURIComponent(active.patient_id)}&encounter=${encodeURIComponent(active.id)}`}>Buka Clinical Assistant <ChevronRight size={15}/></button></>:<div style={{padding:30,textAlign:"center",color:"#7c8799"}}>Belum ada encounter.</div>}</aside></div></section></main>
}
