export type Vitals = { bp?: string; hr?: string; rr?: string; temp?: string; spo2?: string };
export type QuestionAnswer = "yes" | "no" | "unknown";
export type Differential = { name: string; reason: string; level: string; tags: string[] };
export type Investigation = { name: string; reason: string; priority: "Wajib" | "Disarankan" | "Pertimbangkan" };
export type ClinicalQuestion = { id: string; text: string; whyItMatters: string; category: "safety" | "differential" | "disposition" };
export type ClinicalEngineInput = { complaint: string; vitals: Vitals; questionAnswers?: Record<string, QuestionAnswer> };
export type ClinicalEngineResult = {
  engineVersion: string; mode: "rules"; extracted: string[]; missing: string[]; questions: ClinicalQuestion[];
  differentials: Differential[]; investigations: Investigation[]; redFlags: string[]; management: string[]; medicationSafety: string[];
  disposition: { status: "stabilize-first" | "urgent-review" | "routine-review"; title: string; reason: string; triggers: string[] };
  soap: { subjective: string; objective: string; assessment: string; plan: string };
};
const RULE_VERSION = "clinical-rules-v2.2.0";
const norm=(s:string)=>s.toLowerCase().replace(/\s+/g," ").trim();
const yes=(a:QuestionAnswer|undefined)=>a==="yes";
const no=(a:QuestionAnswer|undefined)=>a==="no";
function mention(text:string,terms:string[]){return terms.some(t=>text.includes(t));}
function symptom(text:string,terms:string[]){return terms.some(term=>{const i=text.indexOf(term);if(i<0)return false;const before=text.slice(Math.max(0,i-40),i);return !/(?:\btidak\b|\btanpa\b|\bdisangkal\b|\bmenyangkal\b|\bnegatif\b)(?:\s+ada)?\s*$/.test(before);});}
function num(v?:string){if(!v)return undefined;const n=Number(v.replace(",",".").replace(/[^0-9.\-]/g,""));return Number.isFinite(n)?n:undefined;}
function uniq<T>(xs:T[]){return [...new Set(xs)];}
function pushQ(arr:ClinicalQuestion[],item:ClinicalQuestion){if(!arr.some(x=>x.id===item.id))arr.push(item);}
function makeQ(id:string,text:string,whyItMatters:string,category:ClinicalQuestion["category"]):ClinicalQuestion{return{id,text,whyItMatters,category};}
export function runClinicalEngine(input:ClinicalEngineInput):ClinicalEngineResult{
  const text=norm(input.complaint);const a=input.questionAnswers??{};
  const extracted:string[]=[];const missing:string[]=[];const questions:ClinicalQuestion[]=[];const differentials:Differential[]=[];const investigations:Investigation[]=[];const redFlags:string[]=[];const management:string[]=[];const medicationSafety:string[]=[];
  const fever=symptom(text,["demam","febrile","panas"]),headache=symptom(text,["sakit kepala","nyeri kepala","cephalgia","headache"]),myalgia=symptom(text,["mialgia","nyeri badan","nyeri otot","pegal"]),nausea=symptom(text,["mual","nausea"]),vomiting=symptom(text,["muntah","vomiting"]);
  const cough=symptom(text,["batuk","cough"]),sore=symptom(text,["nyeri tenggorok","sakit tenggorok","radang tenggorok","sore throat"]),rhinitis=symptom(text,["pilek","hidung tersumbat","rhinorrhea","flu"]),bleed=symptom(text,["perdarahan","gusi berdarah","mimisan","melena","hematemesis","muntah darah","bab hitam"]);
  const abdominal=symptom(text,["nyeri perut","sakit perut","abdominal pain"]),diarrhea=symptom(text,["diare","mencret","berak cair","diarrhea"]),dysuria=symptom(text,["nyeri saat kencing","nyeri saat buang air kecil","dysuria","anyang-anyangan"]),frequency=symptom(text,["sering kencing","frekuensi kencing meningkat"]),flank=symptom(text,["nyeri pinggang","nyeri flank","costovertebral"]);
  const dyspnea=symptom(text,["sesak","dispnea","dyspnea","sulit bernapas"]),chest=symptom(text,["nyeri dada","sakit dada","chest pain","tekanan dada"]),palp=symptom(text,["berdebar","palpitasi","palpitation"]),syncope=symptom(text,["pingsan","sinkop","syncope"]),altered=symptom(text,["penurunan kesadaran","bingung","mengantuk berat","kejang"]),focal=symptom(text,["kelemahan satu sisi","mulut mencong","bicara pelo","afasia","baal satu sisi"]);
  const thunder=mention(text,["thunderclap","sangat hebat mendadak","tiba-tiba sangat hebat"]),rash=symptom(text,["ruam","rash","kemerahan kulit"]),allergy=symptom(text,["gatal","urtikaria","biduran","bengkak bibir","bengkak wajah"]),trauma=mention(text,["trauma","jatuh","kecelakaan","terbentur"]);
  const comorb=mention(text,["riwayat penyakit","hipertensi","diabetes","ginjal","asma","jantung","stroke","kanker","hamil","kehamilan"]),allergyHx=mention(text,["alergi","alergi obat","drug allergy"]),meds=mention(text,["obat rutin","obat yang diminum","sedang minum","antikoagulan","aspirin","ibuprofen","warfarin"]);
  const bpSys=num(input.vitals.bp?.split("/")[0]),bpDia=num(input.vitals.bp?.split("/")[1]),hr=num(input.vitals.hr),rr=num(input.vitals.rr),spo2=num(input.vitals.spo2);
  const tachy=typeof hr==="number"&&hr>=100,tachypnea=typeof rr==="number"&&rr>=22,lowSpO2=typeof spo2==="number"&&spo2<92,narrowPP=typeof bpSys==="number"&&typeof bpDia==="number"&&bpSys-bpDia<=25;

  if(fever)pushQ(questions,makeQ("fever-duration","Sudah berapa hari demam berlangsung dan kapan terakhir suhu diukur?","Durasi dan fase demam membantu membentuk konteks differential dan tindak lanjut.","differential"));
  if(fever)pushQ(questions,makeQ("rash","Apakah ada ruam atau kemerahan kulit?","Dapat memperkaya sindrom demam akut dan membantu membedakan beberapa etiologi.","differential"));
  if(fever)pushQ(questions,makeQ("bleeding","Apakah ada perdarahan gusi, hidung, mudah memar, muntah darah, atau BAB hitam?","Perdarahan dapat mengubah urgensi evaluasi dan keamanan obat.","safety"));
  if(fever)pushQ(questions,makeQ("abdominal","Apakah ada nyeri perut hebat atau muntah persisten?","Dapat memengaruhi urgensi evaluasi pada beberapa sindrom demam.","disposition"));
  if(fever)pushQ(questions,makeQ("exposure","Apakah ada paparan sakit serupa, perjalanan, gigitan nyamuk, makanan/air berisiko, atau konteks epidemiologi relevan?","Konteks pajanan membantu mengarahkan differential.","differential"));
  if(cough||sore||rhinitis||dyspnea)pushQ(questions,makeQ("resp-severity","Apakah sesak memburuk, ada sulit bicara karena sesak, atau saturasi rendah bila sudah diperiksa?","Menilai severity dan kebutuhan evaluasi segera.","safety"));
  if(cough||sore||rhinitis||dyspnea)pushQ(questions,makeQ("resp-sputum","Apakah ada dahak purulen, darah pada dahak, mengi, atau stridor?","Membantu memperkaya fokus respirasi dan pemeriksaan.","differential"));
  if(chest)pushQ(questions,makeQ("chest-character","Bagaimana karakter nyeri dada: tertekan/tertindih, pleuritik, positional, atau dipicu aktivitas?","Karakter dan pemicu nyeri membantu mengarahkan differential.","differential"));
  if(chest)pushQ(questions,makeQ("chest-radiation","Apakah nyeri menjalar ke lengan, rahang, punggung, atau disertai keringat dingin/mual?","Gejala penyerta dapat meningkatkan urgensi evaluasi nyeri dada akut.","safety"));
  if(chest)pushQ(questions,makeQ("chest-dyspnea","Apakah disertai sesak, sinkop, palpitasi, atau penurunan toleransi aktivitas?","Membantu menilai kemungkinan penyebab kardiopulmoner yang memerlukan evaluasi lebih cepat.","safety"));
  if(headache)pushQ(questions,makeQ("headache-onset","Apakah sakit kepala muncul mendadak dan mencapai intensitas maksimal dalam waktu singkat?","Onset sangat mendadak merupakan red flag.","safety"));
  if(headache)pushQ(questions,makeQ("headache-neuro","Apakah ada kelemahan satu sisi, gangguan bicara/penglihatan, kejang, atau perubahan kesadaran?","Defisit neurologis akut mengubah urgensi evaluasi.","safety"));
  if(headache)pushQ(questions,makeQ("headache-infection","Apakah ada demam, kaku kuduk, ruam, atau fotofobia?","Membantu membedakan headache primer dari kemungkinan proses sekunder.","differential"));
  if(abdominal)pushQ(questions,makeQ("abd-location","Di mana lokasi nyeri, sejak kapan, dan apakah nyeri berpindah atau semakin berat?","Lokasi, onset, dan progresivitas membantu menentukan fokus pemeriksaan abdomen.","differential"));
  if(abdominal)pushQ(questions,makeQ("abd-peritoneal","Apakah ada nyeri sangat hebat, perut terasa kaku, muntah terus-menerus, atau tidak bisa makan/minum?","Dapat mengubah urgensi evaluasi dan penilaian hidrasi/perfusi.","disposition"));
  if(diarrhea)pushQ(questions,makeQ("diarrhea-dehydration","Apakah ada sangat haus, lemas, jarang kencing, pusing saat berdiri, atau tidak mampu minum?","Menilai kemungkinan dehidrasi.","disposition"));
  if(dysuria||frequency||flank)pushQ(questions,makeQ("urinary-fever","Apakah ada demam, menggigil, mual/muntah, atau nyeri pinggang?","Gejala sistemik dapat menggeser evaluasi ke saluran kemih atas.","safety"));
  if(dysuria||frequency||flank)pushQ(questions,makeQ("urinary-pregnancy","Apakah ada kemungkinan hamil?","Status kehamilan dapat mengubah differential, pemeriksaan, dan terapi.","safety"));
  if(palp||syncope)pushQ(questions,makeQ("cardiac-history","Apakah ada riwayat penyakit jantung, aritmia, atau kematian mendadak dalam keluarga?","Riwayat tersebut dapat mengubah kebutuhan evaluasi kardiovaskular.","safety"));
  if(allergy)pushQ(questions,makeQ("allergy-airway","Apakah ada bengkak lidah/tenggorok, suara serak, sulit bernapas, atau pusing setelah paparan tertentu?","Keterlibatan jalan napas atau sirkulasi dapat merupakan keadaan gawat darurat.","safety"));
  pushQ(questions,makeQ("general-safety","Apakah saat ini ada penurunan kesadaran, kejang, sesak berat, atau kelemahan satu sisi yang baru?","Safety screen umum sebelum finalisasi disposition.","safety"));

  if(fever)extracted.push("Demam");if(headache)extracted.push("Sakit kepala");if(myalgia)extracted.push("Mialgia / nyeri badan");if(nausea)extracted.push("Mual");if(vomiting)extracted.push("Muntah");if(cough)extracted.push("Batuk");if(sore)extracted.push("Nyeri tenggorok");if(rhinitis)extracted.push("Gejala hidung/flu");if(bleed)extracted.push("Gejala perdarahan disebutkan");if(abdominal)extracted.push("Nyeri perut");if(diarrhea)extracted.push("Diare");if(dysuria||frequency)extracted.push("Gejala kemih bawah");if(flank)extracted.push("Nyeri pinggang/flank");if(dyspnea)extracted.push("Sesak/dispnea");if(chest)extracted.push("Nyeri dada");if(palp)extracted.push("Palpitasi");if(syncope)extracted.push("Sinkop/pingsan");if(altered||focal)extracted.push("Temuan neurologis");if(rash)extracted.push("Ruam");if(allergy)extracted.push("Fitur alergi");if(no(a.bleeding))extracted.push("Perdarahan disangkal pada anamnesis terarah");if(no(a["general-safety"]))extracted.push("General red flags disangkal pada anamnesis terarah");
  const vitalLabels:Record<keyof Vitals,string>={bp:"Tekanan darah",hr:"Nadi",rr:"Frekuensi napas",temp:"Suhu",spo2:"SpO₂"};
  (Object.keys(vitalLabels) as (keyof Vitals)[]).forEach(k=>{if(!input.vitals[k])missing.push(vitalLabels[k]);});
  questions.forEach(x=>{if(!a[x.id]||a[x.id]==="unknown")missing.push(`${x.text.replace(/^Apakah /,"")} belum ditentukan`);});
  if(!comorb)missing.push("Riwayat penyakit/komorbid belum jelas");if(!allergyHx)missing.push("Alergi obat belum jelas");if(!meds)missing.push("Obat yang sedang digunakan belum jelas");

  if(fever&&(headache||myalgia||nausea||vomiting||rash))differentials.push({name:"Sindrom dengue / arboviral",reason:"Pola demam akut dengan gejala penyerta dapat sesuai dengan dengue/arboviral dan perlu korelasi klinis, epidemiologi, serta pemeriksaan yang sesuai.",level:"Pertimbangkan",tags:["demam akut",headache?"sakit kepala":myalgia?"mialgia":"gejala penyerta"]});
  if(fever)differentials.push({name:"Sindrom infeksi virus akut",reason:"Demam tanpa fokus infeksi yang jelas dapat sesuai dengan sindrom infeksi virus non-spesifik.",level:"Masih mungkin",tags:["demam","fokus belum jelas"]});
  if(fever&&(nausea||vomiting||abdominal))differentials.push({name:"Infeksi enterik / gastrointestinal",reason:"Demam dengan keluhan gastrointestinal memerlukan korelasi dengan riwayat pajanan dan pemeriksaan klinis.",level:"Pertimbangkan",tags:["demam","gastrointestinal"]});
  if(cough||sore||rhinitis)differentials.push({name:"Infeksi saluran napas akut",reason:"Gejala respirasi atas mengarahkan evaluasi pada fokus saluran napas.",level:"Pertimbangkan",tags:["respirasi"]});
  if(chest)differentials.push({name:"Nyeri dada akut — evaluasi kardiopulmoner",reason:"Nyeri dada memerlukan pemisahan kondisi time-sensitive dari penyebab kardiak, pulmoner, muskuloskeletal, gastrointestinal, dan lainnya.",level:"Evaluasi terarah",tags:["nyeri dada","severity"]});
  if(headache)differentials.push({name:"Headache primer vs sekunder",reason:"Red flag harus dicari sebelum menganggap keluhan sebagai headache primer.",level:"Evaluasi terarah",tags:["onset","neurologis"]});
  if(abdominal)differentials.push({name:"Sindrom nyeri abdomen akut",reason:"Lokasi, onset, progresi, gejala penyerta, dan pemeriksaan fisik menentukan fokus berikutnya.",level:"Evaluasi terarah",tags:["lokasi","abdomen"]});
  if(diarrhea)differentials.push({name:"Diare akut",reason:"Evaluasi perlu menilai pola tinja, dehidrasi, perdarahan, demam, dan paparan.",level:"Pertimbangkan",tags:["diare","hidrasi"]});
  if(dysuria||frequency||flank)differentials.push({name:"Sindrom infeksi saluran kemih",reason:"Keluhan kemih perlu dikorelasikan dengan gejala sistemik dan pemeriksaan urin.",level:"Pertimbangkan",tags:["urin","gejala kemih"]});
  if(palp||syncope)differentials.push({name:"Keluhan kardiovaskular / aritmia",reason:"Palpitasi atau sinkop memerlukan penilaian ritme, hemodinamika, pemicu, dan riwayat kardiak.",level:"Evaluasi terarah",tags:["ritme","hemodinamika"]});
  if(allergy)differentials.push({name:"Reaksi alergi",reason:"Gejala kulit perlu dinilai bersama keterlibatan airway atau sirkulasi.",level:"Pertimbangkan",tags:["kulit","airway"]});
  if(trauma)differentials.push({name:"Cedera terkait trauma",reason:"Mekanisme trauma, lokasi, dan tanda instabilitas perlu dipetakan.",level:"Evaluasi terarah",tags:["mekanisme","red flags"]});
  if(!differentials.length)differentials.push({name:"Keluhan belum terstruktur",reason:"Data belum cukup untuk pertimbangan klinis spesifik pada rule set ini.",level:"Data belum cukup",tags:["anamnesis","tanda vital"]});

  if(lowSpO2)redFlags.push("SpO₂ terukur di bawah 92%: nilai segera status respirasi dan stabilitas klinis sesuai konteks.");if(dyspnea||tachypnea||yes(a["resp-severity"]))redFlags.push("Ada sinyal gangguan respirasi atau peningkatan kerja napas: lakukan penilaian airway-breathing dan severity segera.");if(chest&&(yes(a["chest-radiation"])||yes(a["chest-dyspnea"])))redFlags.push("Nyeri dada dengan gejala penyerta berisiko: prioritaskan evaluasi kardiopulmoner akut.");if(syncope&&(chest||palp||yes(a["cardiac-history"])))redFlags.push("Sinkop dengan fitur kardiak memerlukan evaluasi penyebab kardiovaskular.");if(thunder||yes(a["headache-onset"]))redFlags.push("Sakit kepala dengan onset sangat mendadak merupakan red flag dan memerlukan evaluasi segera.");if(focal||altered||yes(a["headache-neuro"]))redFlags.push("Defisit neurologis fokal, perubahan kesadaran, atau kejang memerlukan evaluasi segera.");if(bleed||yes(a.bleeding))redFlags.push("Perdarahan dilaporkan: nilai sumber, derajat, hemodinamika, dan medication safety.");if(yes(a["abd-peritoneal"])||mention(text,["perut kaku"]))redFlags.push("Nyeri abdomen dengan fitur peritoneal/keparahan tinggi memerlukan evaluasi segera.");if(yes(a["diarrhea-dehydration"]))redFlags.push("Sinyal dehidrasi signifikan dilaporkan pada diare.");if(allergy&&yes(a["allergy-airway"]))redFlags.push("Fitur alergi dengan kemungkinan keterlibatan airway/sirkulasi memerlukan penilaian gawat darurat.");if(narrowPP)redFlags.push("Tekanan nadi tampak menyempit dari input tekanan darah; interpretasikan bersama perfusi dan temuan lain.");if(missing.some(x=>Object.values(vitalLabels).includes(x)))redFlags.push("Tanda vital belum lengkap sehingga stabilitas pasien belum dapat dinilai dari data form.");

  investigations.push({name:"Tanda vital lengkap",reason:"Menilai stabilitas dan severity.",priority:"Wajib"});if(fever)investigations.push({name:"Darah lengkap",reason:"Dipertimbangkan untuk evaluasi sindrom demam sesuai pertanyaan klinis.",priority:"Disarankan"});if(fever&&(headache||myalgia||nausea||vomiting||rash))investigations.push({name:"Hematokrit/trombosit sesuai konteks",reason:"Pertimbangkan bila dengue tetap masuk differential setelah anamnesis dan pemeriksaan fisik.",priority:"Pertimbangkan"});if(cough||dyspnea||sore||rhinitis)investigations.push({name:"Pemeriksaan respirasi terarah",reason:"Sesuaikan dengan kerja napas, suara napas, saturasi, dan faktor risiko.",priority:"Disarankan"});if(chest)investigations.push({name:"Evaluasi nyeri dada akut sesuai kecurigaan klinis",reason:"Pilih pemeriksaan berdasarkan karakter nyeri, faktor risiko, tanda vital, dan temuan fisik.",priority:"Wajib"});if(headache)investigations.push({name:"Pemeriksaan neurologis terarah",reason:"Cari red flags, defisit fokal, meningismus, dan perubahan kesadaran.",priority:"Wajib"});if(abdominal)investigations.push({name:"Pemeriksaan abdomen terarah",reason:"Nilai lokasi nyeri, defense/rigiditas, nyeri tekan, distensi, dan temuan lain.",priority:"Wajib"});if(diarrhea)investigations.push({name:"Penilaian status hidrasi",reason:"Menentukan kebutuhan rehidrasi dan disposition.",priority:"Wajib"});if(dysuria||frequency||flank)investigations.push({name:"Urinalisis sesuai indikasi",reason:"Membantu evaluasi keluhan saluran kemih.",priority:"Disarankan"});if(palp||syncope)investigations.push({name:"EKG / evaluasi ritme sesuai indikasi",reason:"Palpitasi atau sinkop dapat memerlukan evaluasi ritme dan hemodinamika.",priority:"Disarankan"});

  management.push("Lengkapi anamnesis terarah dan pemeriksaan fisik sebelum menetapkan diagnosis kerja atau disposition.");if(lowSpO2||dyspnea||tachypnea)management.push("Prioritaskan penilaian airway-breathing, oksigenasi, dan severity sesuai kondisi pasien.");if(fever)management.push("Untuk sindrom demam, pertimbangkan terapi suportif, hidrasi sesuai status klinis, monitoring, dan edukasi tanda bahaya.");if(chest)management.push("Pada nyeri dada, prioritaskan pemisahan kondisi time-sensitive sebelum terapi simptomatik rutin.");if(diarrhea)management.push("Pada diare, fokus awal pada status hidrasi, kemampuan intake, frekuensi/karakter tinja, dan tanda infeksi/perdarahan.");management.push("Review ulang differential setelah jawaban anamnesis, pemeriksaan fisik, dan hasil penunjang baru tersedia.");
  medicationSafety.push("Konfirmasi alergi obat dan obat yang sedang digunakan sebelum meresepkan atau mengubah terapi.");medicationSafety.push("Periksa kontraindikasi, interaksi, fungsi ginjal/hati, usia, kehamilan, dan kondisi khusus yang relevan.");if(bleed||yes(a.bleeding))medicationSafety.push("Dengan sinyal perdarahan, lakukan review obat yang dapat meningkatkan risiko perdarahan.");

  let disposition:ClinicalEngineResult["disposition"];const critical=redFlags.filter(x=>!x.startsWith("Tanda vital belum lengkap"));if(critical.length)disposition={status:"stabilize-first",title:"Prioritaskan stabilisasi & evaluasi segera",reason:"Terdapat sinyal klinis yang memerlukan penilaian segera atau dapat berkaitan dengan kondisi time-sensitive.",triggers:critical.slice(0,5)};else if(missing.length||redFlags.length)disposition={status:"urgent-review",title:"Review klinis sebelum finalisasi",reason:"Data penting masih belum lengkap dan/atau ada keterbatasan yang perlu direview.",triggers:missing.slice(0,5)};else disposition={status:"routine-review",title:"Lanjutkan review klinis terstruktur",reason:"Data inti pada form lebih lengkap, tetapi diagnosis kerja dan disposition tetap merupakan keputusan dokter.",triggers:[]};
  const objectiveParts:string[]=[];if(Object.values(input.vitals).some(Boolean))objectiveParts.push(`TD ${input.vitals.bp||"—"}, nadi ${input.vitals.hr||"—"}/menit, RR ${input.vitals.rr||"—"}/menit, suhu ${input.vitals.temp||"—"}°C, SpO₂ ${input.vitals.spo2||"—"}%.`);if(missing.length)objectiveParts.push(`Data belum lengkap: ${missing.slice(0,6).join(", ")}.`);objectiveParts.push("Pemeriksaan fisik perlu didokumentasikan langsung oleh dokter.");
  return {engineVersion:RULE_VERSION,mode:"rules",extracted:uniq(extracted),missing:uniq(missing),questions,differentials:differentials.slice(0,8),investigations,redFlags:uniq(redFlags),management,medicationSafety,disposition,soap:{subjective:input.complaint.trim()||"Keluhan belum diisi.",objective:objectiveParts.join(" "),assessment:`Pertimbangan rule engine: ${differentials.map(x=>x.name).join(", ")}. Diagnosis kerja final tidak ditetapkan otomatis.`,plan:`${investigations.map(x=>`${x.priority}: ${x.name}`).join("; ")} ${management.join(" ")} Disposition support: ${disposition.title}.`}};
}
