"use client";

import { useState } from "react";
import { Activity, ArrowLeft, Calculator, CheckSquare, ClipboardList, FileText, Search, Stethoscope } from "lucide-react";

const tools=[
 {title:"SOAP Builder",desc:"Susun draft Subjective, Objective, Assessment, dan Plan sebelum dokumentasi final.",icon:FileText,cta:"Buka SOAP Builder"},
 {title:"Clinical Checklist",desc:"Checklist pemeriksaan, safety review, dan dokumentasi agar langkah penting tidak terlewat.",icon:CheckSquare,cta:"Buka Checklist"},
 {title:"Drug Lookup",desc:"Ruang pencarian database obat. Dosis dan keputusan terapi tetap diverifikasi terhadap sumber klinis.",icon:Search,cta:"Buka Drug Lookup"},
 {title:"Clinical Calculator",desc:"Modul kalkulator klinis disiapkan untuk diisi dengan rumus dan sumber yang tervalidasi.",icon:Calculator,cta:"Buka Calculator"},
];
export default function ToolsPage(){const [open,setOpen]=useState<string|null>(null);const [soap,setSoap]=useState({s:"",o:"",a:"",p:""});return <main style={page}><header style={header}><a href="/" style={back}><ArrowLeft size={14}/> Dashboard</a><div><div style={eyebrow}>CLINICAL TOOLS</div><h1 style={h1}>Tools</h1></div></header><div style={wrap}>{open===null?<div style={grid}>{tools.map(({title,desc,icon:Icon,cta})=><button key={title} onClick={()=>setOpen(title)} style={tool}><div style={icon}><Icon size={19}/></div><div style={{textAlign:"left"}}><b>{title}</b><span>{desc}</span><em>{cta} →</em></div></button>)}</div>:open==="SOAP Builder"?<section style={card}><div style={head}><div><div style={eyebrow}>SOAP BUILDER</div><h2 style={h2}>Draft SOAP</h2><span style={muted}>Isi manual dan review sebelum dipindahkan ke rekam medis.</span></div><button onClick={()=>setOpen(null)} style={secondary}>Kembali</button></div>{([['s','S — Subjective'],['o','O — Objective'],['a','A — Assessment'],['p','P — Plan']] as const).map(([k,label])=><label key={k} style={labelStyle}>{label}<textarea value={soap[k]} onChange={e=>setSoap({...soap,[k]:e.target.value})} style={textarea}/></label>)}<div style={preview}><b>Preview</b><pre>{`S: ${soap.s}\nO: ${soap.o}\nA: ${soap.a}\nP: ${soap.p}`}</pre></div></section>:<section style={card}><div style={head}><div><div style={eyebrow}>MODULE</div><h2 style={h2}>{open}</h2></div><button onClick={()=>setOpen(null)} style={secondary}>Kembali</button></div><div style={empty}><Stethoscope size={20}/><p>Modul sudah disiapkan sebagai segmen terpisah. Implementasi data/rules tervalidasi akan ditempatkan di sini tanpa mengisi nilai klinis secara asumtif.</p></div></section>}</div></main>}
const page={minHeight:"100vh",background:"#f5f8fc",fontFamily:"Inter,Arial,sans-serif",color:"#16213d"};const header={height:64,background:"#fff",borderBottom:"1px solid #e5eaf2",display:"flex",alignItems:"center",gap:18,padding:"0 28px"};const back={display:"flex",gap:6,alignItems:"center",fontSize:10,color:"#65728a",textDecoration:"none"};const eyebrow={fontSize:8,fontWeight:800,letterSpacing:".12em",color:"#6a81a7"};const h1={margin:"3px 0",fontSize:20,color:"#10295b"};const wrap={maxWidth:1120,margin:"22px auto",padding:"0 14px"};const grid={display:"grid",gridTemplateColumns:"1fr 1fr",gap:12};const tool={border:"1px solid #e1e7f0",background:"#fff",borderRadius:14,padding:16,display:"flex",gap:12,alignItems:"flex-start",cursor:"pointer",boxShadow:"0 3px 15px rgba(23,37,84,.03)"};const icon={width:38,height:38,borderRadius:11,background:"#eef4ff",color:"#2563eb",display:"grid",placeItems:"center",flex:"0 0 auto"};const card={background:"#fff",border:"1px solid #e1e7f0",borderRadius:14,padding:15};const head={display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start",marginBottom:12};const h2={margin:0,fontSize:14,color:"#10295b"};const muted={display:"block",marginTop:4,fontSize:8,color:"#8792a4"};const labelStyle={display:"block",fontSize:8,fontWeight:700,color:"#68758a",marginTop:9};const textarea={display:"block",width:"100%",minHeight:75,boxSizing:"border-box",marginTop:5,border:"1px solid #dce3ee",borderRadius:8,padding:9,fontSize:9,resize:"vertical" as const,outline:0};const primary={border:0,background:"#2563eb",color:"#fff",borderRadius:8,padding:"9px 11px",fontSize:9,fontWeight:700};const secondary={border:"1px solid #dce3ee",background:"#fff",color:"#617089",borderRadius:8,padding:"8px 10px",fontSize:9,fontWeight:700,cursor:"pointer"};const preview={marginTop:12,border:"1px solid #e4e9f0",background:"#f8fafc",padding:10,borderRadius:9,fontSize:8};const empty={border:"1px dashed #dce3ee",borderRadius:10,padding:25,textAlign:"center",color:"#8792a4",fontSize:10};
