"use client";

import { useState, type CSSProperties } from "react";
import { ArrowLeft, Check, ClipboardList, Save, ShieldCheck, Trash2 } from "lucide-react";
import { deletePrescription, listPrescriptions, savePrescription, type Prescription } from "../../lib/prescription-storage";

export default function PrescriptionsPage(){
 const [items,setItems]=useState<Prescription[]>(()=>listPrescriptions());
 const [form,setForm]=useState({patientName:"",medicalRecordNumber:"",medication:"",strength:"",dose:"",route:"",frequency:"",duration:"",instruction:""});
 const [notice,setNotice]=useState("");
 const set=(key:string,value:string)=>setForm({...form,[key]:value});
 const save=()=>{if(!form.patientName.trim()||!form.medication.trim()){setNotice("Nama pasien dan nama obat wajib diisi.");return;} const x=savePrescription({...form,reviewed:false}); setItems(listPrescriptions()); setNotice(`Draft resep untuk ${x.patientName} tersimpan.`); setForm({patientName:"",medicalRecordNumber:"",medication:"",strength:"",dose:"",route:"",frequency:"",duration:"",instruction:""});};
 return <main style={page}><header style={header}><a href="/" style={back}><ArrowLeft size={14}/> Dashboard</a><div><div style={eyebrow}>PRESCRIPTION WORKSPACE</div><h1 style={h1}>Resep</h1></div></header><div style={wrap}>
  {notice&&<div style={noticeStyle}>{notice}</div>}
  <div style={grid}><section style={card}><div style={head}><div><h2 style={h2}>Buat draft resep</h2><span style={muted}>Dokumentasi resep dengan checklist review. Dosis tidak diisi otomatis.</span></div><ClipboardList size={18} color="#2563eb"/></div>
   <div style={fields}>{([['patientName','Nama pasien','text'],['medicalRecordNumber','No. RM','text'],['medication','Nama obat','text'],['strength','Kekuatan','text'],['dose','Dosis per pemberian','text'],['route','Rute','text'],['frequency','Frekuensi','text'],['duration','Durasi','text']] as const).map(([key,label,type])=><label key={key} style={labelStyle}>{label}<input type={type} value={form[key]} onChange={e=>set(key,e.target.value)} placeholder={label} style={input}/></label>)}</div>
   <label style={labelStyle}>Instruksi / signa<textarea value={form.instruction} onChange={e=>set("instruction",e.target.value)} placeholder="Instruksi penggunaan, edukasi, atau catatan dokter..." style={textarea}/></label>
   <div style={safety}><ShieldCheck size={15}/><div><b>Prescription safety</b><span>Review indikasi, alergi, interaksi, kontraindikasi, usia/berat badan, fungsi ginjal/hati, kehamilan, dan sumber guideline sebelum sign.</span></div></div>
   <button onClick={save} style={primary}><Save size={14}/> Simpan Draft Resep</button>
  </section><section style={card}><div style={head}><div><h2 style={h2}>Draft tersimpan</h2><span style={muted}>Disimpan lokal pada browser ini.</span></div><span style={badge}>{items.length} draft</span></div>{items.length===0?<div style={empty}>Belum ada draft resep.</div>:items.map(x=><article key={x.id} style={rxCard}><div style={rxTop}><div><b>{x.medication}{x.strength?` · ${x.strength}`:""}</b><span>{x.patientName} · {x.medicalRecordNumber||"No. RM —"}</span></div><button onClick={()=>{deletePrescription(x.id);setItems(listPrescriptions());}} style={danger}><Trash2 size={13}/></button></div><div style={rxLine}><span>{x.dose||"Dosis —"}</span><span>{x.route||"Rute —"}</span><span>{x.frequency||"Frekuensi —"}</span><span>{x.duration||"Durasi —"}</span></div>{x.instruction&&<p style={small}>{x.instruction}</p>}<div style={review}><Check size={12}/> Belum menggantikan review dokter</div></article>)}</section></div>
 </div></main>;
}
const page:CSSProperties={minHeight:"100vh",background:"#f5f8fc",fontFamily:"Inter,Arial,sans-serif",color:"#16213d"};const header:CSSProperties={height:64,background:"#fff",borderBottom:"1px solid #e5eaf2",display:"flex",alignItems:"center",gap:18,padding:"0 28px"};const back:CSSProperties={display:"flex",alignItems:"center",gap:6,textDecoration:"none",color:"#65728a",fontSize:10};const eyebrow:CSSProperties={fontSize:8,fontWeight:800,letterSpacing:".12em",color:"#6a81a7"};const h1:CSSProperties={margin:"3px 0",fontSize:20,color:"#10295b"};const wrap:CSSProperties={maxWidth:1120,margin:"22px auto",padding:"0 14px"};const grid:CSSProperties={display:"grid",gridTemplateColumns:"1.15fr .85fr",gap:13};const card:CSSProperties={background:"#fff",border:"1px solid #e1e7f0",borderRadius:14,padding:15};const head:CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:10,marginBottom:12};const h2:CSSProperties={margin:0,fontSize:14,color:"#10295b"};const muted:CSSProperties={display:"block",marginTop:4,fontSize:8,color:"#8792a4",lineHeight:1.45};const fields:CSSProperties={display:"grid",gridTemplateColumns:"1fr 1fr",gap:8};const labelStyle:CSSProperties={display:"block",fontSize:8,fontWeight:700,color:"#69768b"};const input:CSSProperties={width:"100%",boxSizing:"border-box",marginTop:5,border:"1px solid #dce3ee",borderRadius:7,padding:"8px 9px",fontSize:9,outline:0,color:"#22304a"};const textarea:CSSProperties={...input,minHeight:80,resize:"vertical"};const safety:CSSProperties={display:"flex",gap:8,background:"#eef9f6",border:"1px solid #ccebe2",borderRadius:9,padding:10,color:"#257766",fontSize:8,lineHeight:1.45,margin:"10px 0"};const primary:CSSProperties={border:0,background:"#2563eb",color:"#fff",borderRadius:8,padding:"9px 11px",fontSize:9,fontWeight:700,display:"inline-flex",alignItems:"center",gap:6,cursor:"pointer"};const badge:CSSProperties={background:"#eef4ff",color:"#526d9f",padding:"5px 7px",borderRadius:5,fontSize:8,fontWeight:700};const empty:CSSProperties={padding:32,textAlign:"center",color:"#8792a4",fontSize:10};const rxCard:CSSProperties={borderTop:"1px solid #edf0f4",padding:"11px 0"};const rxTop:CSSProperties={display:"flex",justifyContent:"space-between",gap:8};const rxLine:CSSProperties={display:"flex",gap:5,flexWrap:"wrap",marginTop:8};const review:CSSProperties={display:"inline-flex",alignItems:"center",gap:4,background:"#f5f7fa",color:"#718096",padding:"4px 6px",borderRadius:5,fontSize:7,marginTop:7};const small:CSSProperties={fontSize:8,color:"#8792a4",lineHeight:1.5};const danger:CSSProperties={border:"1px solid #f0d2d2",background:"#fff",color:"#bf4d4d",borderRadius:7,padding:"6px 8px",cursor:"pointer"};const noticeStyle:CSSProperties={background:"#eef5ff",border:"1px solid #d8e6ff",color:"#315b9f",borderRadius:9,padding:"9px 11px",fontSize:9,marginBottom:12};