"use client";

import { useMemo, useState } from "react";
import { BookOpen, Check, Clipboard, FileText, Search, Stethoscope } from "lucide-react";
const templates=[
 {id:"soap",name:"SOAP Visit",cat:"Dokumentasi",desc:"Catatan S/O/A/P untuk outpatient encounter",body:"S: Keluhan utama dan riwayat penyakit sekarang.\nO: Tanda vital dan pemeriksaan fisik.\nA: Diagnosis kerja + diagnosis banding relevan.\nP: Pemeriksaan, terapi, edukasi, follow-up."},
 {id:"ref",name:"Surat Rujukan",cat:"Administratif klinis",desc:"Rujukan dengan ringkasan klinis",body:"Yth. Dokter Spesialis...\nIdentitas pasien:\nKeluhan utama:\nTemuan penting:\nDiagnosis kerja:\nTerapi yang telah diberikan:\nMohon evaluasi dan tata laksana lebih lanjut."},
 {id:"discharge",name:"Edukasi Pulang",cat:"Edukasi",desc:"Safety-net dan instruksi follow-up",body:"Diagnosis/kondisi:\nObat sesuai resep:\nAnjuran aktivitas/nutrisi:\nKontrol:\nKembali segera bila muncul red flags atau kondisi memburuk."},
 {id:"certificate",name:"Surat Keterangan",cat:"Administratif",desc:"Draft surat keterangan medis",body:"Yang bertanda tangan di bawah ini menerangkan bahwa:\nNama:\nNo. RM:\nTelah menjalani pemeriksaan pada tanggal:\nKeterangan:\nDokumen ini harus direview dan ditandatangani dokter."},
];
export default function TemplatesPage(){const [q,setQ]=useState("");const [sel,setSel]=useState(templates[0]);const filtered=useMemo(()=>templates.filter(t=>(t.name+t.cat+t.desc).toLowerCase().includes(q.toLowerCase())),[q]);return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">D</div><div><strong>Dokter Jaga</strong><span>Clinical Intelligence</span></div></div><nav><a className="nav-item" href="/">⌂ Beranda</a><a className="nav-item" href="/patients">◯ Pasien</a><a className="nav-item" href="/records">▤ Rekam Medis</a><a className="nav-item" href="/prescriptions">◒ Resep</a><a className="nav-item" href="/clinical">♥ Clinical Assistant<i>AI</i></a><a className="nav-item" href="/tools">⌘ Tools</a><a className="nav-item active" href="/templates"><BookOpen size={17}/>Template</a></nav><div className="sidebar-bottom"><a className="nav-item" href="/schedule">◷ Jadwal</a><a className="nav-item" href="/reports">◫ Laporan</a><a className="nav-item" href="/settings">⚙ Pengaturan</a></div></aside><section className="content"><header className="topbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari template..."/></div></header><div className="page-head"><div><p className="eyebrow">CLINICAL TEMPLATES</p><h1>Template</h1><p className="muted">Template kerja untuk mempercepat dokumentasi tanpa menghilangkan review dokter.</p></div><button className="primary" onClick={()=>alert("Custom template: tahap berikutnya")}>+ Custom Template</button></div><div className="workspace-grid" style={{gridTemplateColumns:".7fr 1.3fr",alignItems:"start"}}><section className="panel" style={{padding:16}}><div className="panel-head"><div><h2>Library</h2><p>{filtered.length} template</p></div></div>{filtered.map(t=><button className="patient-row" key={t.id} onClick={()=>setSel(t)}><div className="quick-icon blue" style={{width:32,height:32}}><FileText size={15}/></div><div className="patient-info"><b>{t.name}</b><span>{t.cat} · {t.desc}</span></div></button>)}</section><section className="panel" style={{padding:18}}><div className="panel-head"><div><p className="eyebrow">TEMPLATE PREVIEW</p><h2>{sel.name}</h2></div><button className="text-btn" onClick={()=>navigator.clipboard?.writeText(sel.body)}><Clipboard size={13}/> Copy</button></div><div className="clinical-input" style={{minHeight:260}}><textarea defaultValue={sel.body} style={{width:"100%",minHeight:240,border:0,outline:0,resize:"vertical",fontSize:10,lineHeight:1.7,color:"#39445b"}}/></div><div className="trust-note" style={{marginTop:10}}><Stethoscope size={16}/><span><strong>Workflow:</strong> isi → review → edit bila perlu → sign. Template bukan catatan final sampai ditandatangani.</span></div></section></div></section></main>}
